"use client";

import { useEffect, useRef, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import Link from "next/link";
import { signIn } from "next-auth/react";
import BrandMark from "@/components/BrandMark";
import { ApiError, guestLogin, joinTrip, previewJoin } from "@/lib/api";
import { getGuestToken, markHasSessionCookie, setBackendToken, setGuestName, setGuestToken } from "@/lib/authToken";
import { useAuthIdentity } from "@/lib/useAuthIdentity";

/**
 * Landing page for an invite link (`{origin}/join/{code}`, generated by
 * components/settings/PeopleSection.tsx's "產生邀請連結" button).
 *
 * This route is PUBLIC (see auth.config.ts — `/join/*` is allow-listed) so a
 * brand-new, not-yet-logged-in visitor can land here straight from a shared
 * link and see an unauthenticated preview (GET /api/trips/join/preview, no
 * login required — see backend/app/routers/trips.py join_preview) of what
 * they're about to join BEFORE committing to a login method:
 *
 *   - Already logged in with Google (identity.kind === "google"): redeem
 *     the code immediately via the existing name-match-then-create logic
 *     (no picker — a Google account's real name is a reliable enough
 *     auto-match signal).
 *   - Not logged in / guest: shows "你要加入『{trip_name}』" with two paths —
 *     "使用 Google 帳號登入並加入" (kicks off the normal Google login flow,
 *     with this same URL as the callback, so control returns here and the
 *     Google branch above takes over) or "使用訪客身分加入".
 *
 * This round's "訪客也能是完整成員" simplification removes the "你是這趟
 * 行程裡的哪一位？" member picker from the guest path entirely — a guest is
 * NEVER a split-accounting Member (see backend models.TripAccess's
 * "contributor" role docstring), so "which existing member is this guest"
 * is no longer a question that applies.
 *
 * This later round's "訪客不該有任何帳號感" simplification goes one step
 * further and removes the guest display-name step too — a guest is now
 * always just "訪客", no naming prompt, no sense of "account" at all. The
 * guest path is now a single click: "使用訪客身分加入" -> POST
 * /api/auth/guest (no `name`) -> POST /api/trips/join (no claim_member_id)
 * -> land straight on the expenses page with "contributor" access.
 */
type Step =
  | "loading"
  | "error"
  | "auto-joining" // already logged in with Google — redeeming immediately
  | "choose" // "你要加入『{trip_name}』" — pick Google login vs guest
  | "submitting"; // guestLogin + joinTrip in flight

export default function JoinTripPage() {
  const params = useParams<{ code: string }>();
  const router = useRouter();
  const identity = useAuthIdentity();
  const code = params?.code ?? "";

  const [step, setStep] = useState<Step>("loading");
  const [error, setError] = useState<string | null>(null);
  const [tripName, setTripName] = useState("");

  const autoJoinAttempted = useRef(false);
  const previewAttempted = useRef(false);

  // Fetch the unauthenticated preview once, regardless of identity — even
  // the Google auto-join path needs `code` validated first (an invalid code
  // should show the same clear error either way, not a raw joinTrip 404).
  useEffect(() => {
    if (!code || previewAttempted.current) return;
    previewAttempted.current = true;
    previewJoin(code)
      .then((p) => {
        setTripName(p.trip_name);
        setStep((s) => (s === "loading" ? "choose" : s));
      })
      .catch((e) => {
        setError(e instanceof ApiError ? e.message : "邀請連結無效，請確認連結是否正確");
        setStep("error");
      });
  }, [code]);

  // Once BOTH the preview resolved successfully AND we know this browser is
  // already logged in with a real Google session, skip straight to redeeming
  // the code — no picker (see this file's top docstring).
  useEffect(() => {
    if (step !== "choose" || identity.kind !== "google" || autoJoinAttempted.current) return;
    autoJoinAttempted.current = true;
    setStep("auto-joining");
    joinTrip(code)
      .then((trip) => router.replace(`/trips/${trip.id}`))
      .catch((e) => {
        setError(e instanceof ApiError ? e.message : "加入行程失敗，請確認邀請連結是否正確");
        setStep("error");
      });
  }, [step, identity.kind, code, router]);

  const startGoogleLogin = () => {
    signIn("google", { callbackUrl: typeof window !== "undefined" ? window.location.pathname : `/join/${code}` });
  };

  const startGuestFlow = () => {
    setError(null);
    finishGuestJoin();
  };

  const finishGuestJoin = async () => {
    setStep("submitting");
    setError(null);
    try {
      let token = getGuestToken();
      if (!token) {
        // Brand-new guest identity for this browser — no name prompt at all
        // anymore (this round's "訪客不該有任何帳號感" simplification):
        // every guest is just "訪客", resolved entirely server-side (see
        // backend routers/auth.py guest_login's default-name fallback).
        const res = await guestLogin();
        token = res.token;
        setGuestToken(token);
        setGuestName(res.user.name);
        markHasSessionCookie();
        setBackendToken(token);
      } else {
        // Already a guest in this browser (e.g. returning to a second
        // invite link) — reuse the identity as-is.
        setBackendToken(token);
      }
      // No claim_member_id — a guest is never linked to a Member (see
      // backend join_trip's is_guest branch / models.TripAccess's
      // "contributor" role docstring).
      const trip = await joinTrip(code);
      router.replace(`/trips/${trip.id}`);
    } catch (e) {
      setError(e instanceof ApiError ? e.message : e instanceof Error ? e.message : "加入行程失敗，請稍後再試");
      setStep("error");
    }
  };

  return (
    <div className="min-h-screen flex items-center justify-center bg-slate-50 px-4">
      <div className="w-full max-w-sm bg-white rounded-2xl border border-slate-200 shadow-sm p-8 flex flex-col items-center text-center">
        <BrandMark className="w-14 h-14" rounded="rounded-2xl" />

        {(step === "loading" || step === "auto-joining" || step === "submitting") && (
          <>
            <p className="mt-4 text-slate-700 font-semibold">
              {step === "loading" ? "正在讀取邀請連結…" : "正在加入行程…"}
            </p>
            <p className="mt-1 text-sm text-slate-400">請稍候</p>
          </>
        )}

        {step === "choose" && (
          <>
            <p className="mt-4 text-lg font-bold text-slate-900">你要加入「{tripName}」</p>
            <p className="mt-1.5 text-[13px] text-slate-500">選擇一種方式加入這趟行程</p>
            <button
              type="button"
              onClick={startGoogleLogin}
              className="mt-6 w-full inline-flex items-center justify-center gap-2.5 border border-slate-300 rounded-lg px-4 py-2.5 text-sm font-medium text-slate-700 hover:bg-slate-50 shadow-sm"
            >
              <svg viewBox="0 0 24 24" className="w-4.5 h-4.5" aria-hidden="true">
                <path
                  fill="#4285F4"
                  d="M23.52 12.27c0-.85-.08-1.67-.22-2.45H12v4.64h6.47a5.54 5.54 0 0 1-2.4 3.64v3h3.88c2.27-2.09 3.57-5.17 3.57-8.83z"
                />
                <path
                  fill="#34A853"
                  d="M12 24c3.24 0 5.96-1.07 7.95-2.9l-3.88-3c-1.08.72-2.45 1.15-4.07 1.15-3.13 0-5.78-2.11-6.73-4.96H1.26v3.11A11.99 11.99 0 0 0 12 24z"
                />
                <path
                  fill="#FBBC05"
                  d="M5.27 14.29A7.2 7.2 0 0 1 4.89 12c0-.8.14-1.57.38-2.29V6.6H1.26A11.99 11.99 0 0 0 0 12c0 1.94.46 3.77 1.26 5.4l4.01-3.11z"
                />
                <path
                  fill="#EA4335"
                  d="M12 4.75c1.77 0 3.35.61 4.6 1.8l3.44-3.44C17.95 1.19 15.24 0 12 0 7.31 0 3.26 2.69 1.26 6.6l4.01 3.11C6.22 6.86 8.87 4.75 12 4.75z"
                />
              </svg>
              使用 Google 帳號登入並加入
            </button>
            <div className="mt-4 flex items-center gap-3 w-full">
              <div className="flex-1 h-px bg-slate-200" />
              <span className="text-[11px] text-slate-400">或</span>
              <div className="flex-1 h-px bg-slate-200" />
            </div>
            <button
              type="button"
              onClick={startGuestFlow}
              className="mt-4 w-full inline-flex items-center justify-center bg-teal-600 hover:bg-teal-700 text-white rounded-lg px-4 py-2.5 text-sm font-medium shadow-sm"
            >
              使用訪客身分加入
            </button>
            <p className="mt-2.5 text-[11px] text-slate-400 leading-relaxed">
              訪客身分只能記帳、看結算，不能編輯既有支出或行程設定
            </p>
          </>
        )}

        {step === "error" && (
          <>
            <p className="mt-4 text-slate-900 font-semibold">邀請連結無效</p>
            <p className="mt-1 text-sm text-rose-600">{error}</p>
            <p className="mt-1 text-xs text-slate-400">連結可能已失效，請向行程擁有者重新索取邀請連結。</p>
            <Link
              href="/"
              className="mt-6 inline-flex items-center justify-center bg-teal-600 hover:bg-teal-700 text-white rounded-lg px-4 py-2.5 text-sm font-medium shadow-sm"
            >
              回到首頁
            </Link>
          </>
        )}
      </div>
    </div>
  );
}
